accounts/urls.py
from django.urls import path
from . import views

# used for namespacing applications
app_name = 'accounts'

# path: 4 args, first 2 required
# 1st: route = contains a URL pattern (localhost:8000/'route')
# 2nd: view = calls the matched specified function
# 3rd: kwargs = ?
# 4th: name = naming your urls lets you refer to it unambigiously from elsewehere in django (templates)
urlpatterns = [
    path("register", views.register, name='register'),
    path("login", views.login, name="login"),
    path("logout", views.logout, name="logout")
]

accounts/models.py
from django.db import models

# Create your models here.

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.contrib.auth.models import User, auth
from django.contrib import messages

# Create your views here.

def register(request):
    # When submitted
    if request.method == 'POST':
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        username = request.POST['username']
        email = request.POST['email']
        password1 = request.POST['password1']
        password2 = request.POST['password2']

        # Confirm password is different
        if password1 != password2:     
            messages.info(request, 'Passwords don\'t match')           
            return redirect('accounts:register')
            
        # Username taken
        elif User.objects.filter(username=username).exists():    
            messages.info(request, 'Username already taken')           
            return redirect('accounts:register')

        # Email taken
        elif User.objects.filter(email=email).exists():
            messages.info(request, 'Email already taken')           
            return redirect('accounts:register')

        # Save new user
        else:
            user = User.objects.create_user(username=username, password=password1, 
                                email=email, first_name=first_name, last_name=last_name)
            return redirect('accounts:login')

    # Register page
    else:
        return render(request, 'register.html')

def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        print("username: " + username + ", password: " + password)

        user = authenticate(username=username, password=password)

        if user is not None:
            auth.login(request, user)
            return redirect('webapp:index')
        else:
            messages.info(request, "Invalid credentials")
            return redirect('accounts:login')
    else:
        return render(request, 'login.html')

def logout(request):
    auth.logout(request)
    return redirect('webapp:index')

accounts/templates/accounts/base.html
{% load static %}

<!-- MIT Licenced template: https://startbootstrap.com/template/bare -->

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block title %}{% endblock %}</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'webapp/assets/favicon.ico' %}" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'webapp/css/styles.css' %}" rel="stylesheet" />
    <body>
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="{% url 'webapp:index' %}">Bachelor Project</a>
                <!-- {% if user.is_authenticated %}
                    <li class="navbar-text">User: {{ user.first_name }} {{ user.last_name }}</li>
                {% endif %} -->
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        {% if user.is_authenticated %}
                            <li class="navbar-text">Hello, {{ user.first_name }}&nbsp;&nbsp;&nbsp;</li>
                            <!-- <li class="nav-item"><a class="nav-link" href="#">Link</a></li> -->
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Menu</a>
                                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                    <li><a class="dropdown-item" href="{% url 'webapp:upload' %}">Upload File</a></li>
                                    <!-- <li><a class="dropdown-item" href="#">Remove File</a></li> -->
                                    <li><a class="dropdown-item" href="{% url 'webapp:file_list' %}">All Files</a></li>
                                    <li><hr class="dropdown-divider" /></li>
                                    <li><a class="dropdown-item" href="{% url 'accounts:logout' %}">Log out</a></li>
                                </ul>
                            </li>
                        {% else %}
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'accounts:login' %}">Login</a></li>
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'accounts:register' %}">Register</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page content-->
        <div class="container">
            <div id="content" class="text-center-start mt-5">
                {% block content %}
                {% endblock %}
            </div>
        </div>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'webapp/js/scripts.js' %}"></script>
    </body>
</html>

accounts/templates/accounts/login.html
{% extends "base.html" %}

{% load static %}

{% load crispy_forms_tags %}

{% block title %} Login Page {% endblock %}

{% block content %}

<h1>Login</h1>

<br>
<div class="container">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row">
            <div class="col-25">
                <label>Username</label>
            </div>
            <div class="col-75">
                <input type="text" name="username" placeholder="Your username">
            </div>
        </div>
        <div class="row">
            <div class="col-25">
                <label>Password</label>
            </div>
            <div class="col-75">
                <input type="password" name="password" placeholder="Your password">
            </div>
        </div>
        <div>
            <br>
            <button type="submit" class="btn btn-secondary btn-sm" autofocus="True">Log in</button>
        </div>
    </form>
</div>

<br>
<div>
    {% for message in messages %}
        <p style="color:white; background-color: tomato; border-radius: 5px;">&nbsp;Error: {{ message }} </p>
    {% endfor %}
</div>

{% endblock %} 

accounts/templates/accounts/register.html
{% extends "base.html" %}

{% load static %}

{% load crispy_forms_tags %}

{% block title %} Register Page {% endblock %}

{% block content %}

<h1>Register an Account</h1>

<br>
<!-- <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <p>First Name: <input type="text" name="first_name" placeholder="First Name"></p>
    <p>Last Name: <input type="text" name="last_name" placeholder="Last Name"></p>
    <p>Username: <input type="text" name="username" placeholder="Username"></p>
    <p>Email: <input type="email" name="email" placeholder="email"></p>
    <p>Password: <input type="password" name="password1" placeholder="Password"></p>
    <p>Confirm Password: <input type="password" name="password2" placeholder="Confirm Password"></p>

    <br>
    <button type="submit" class="btn btn-secondary btn-sm" autofocus="True">Register</button>
</form> -->

<div class="container">
    <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
        <div class="row">
            <div class="col-25">
                <label>First Name</label>
            </div>
            <div class="col-75">
                <input type="text" name="first_name" placeholder="Your name">
            </div>
        </div>
        <div class="row">
            <div class="col-25">
                <label>Last Name</label>
            </div>
            <div class="col-75">
                <input type="text" name="last_name" placeholder="Your last name">
            </div>
        </div>
        <div class="row">
            <div class="col-25">
                <label>Username</label>
            </div>
            <div class="col-75">
                <input type="text" name="username" placeholder="Your username">
            </div>
        </div>
        <div class="row">
            <div class="col-25">
                <label>Email</label>
            </div>
            <div class="col-75">
                <input type="email" name="email" placeholder="Your email">
            </div>
        </div>
        <div class="row">
            <div class="col-25">
                <label>Password</label>
            </div>
            <div class="col-75">
                <input type="password" name="password1" placeholder="">
            </div>
        </div>
        <div class="row">
            <div class="col-25">
                <label>Confirm password</label>
            </div>
            <div class="col-75">
                <input type="password" name="password2" placeholder="">
            </div>
        </div>
        <div>
            <br>
            <button type="submit" class="btn btn-secondary btn-sm" autofocus="True">Register</button>
        </div>
    </form>
</div>

<br>
<div>
    {% for message in messages %}
        <p style="color:white; background-color: tomato; border-radius: 5px;">&nbsp;Error: {{ message }} </p>
    {% endfor %}
</div>

<br>
<br>

{% endblock %} 