app/appPackage/application/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


# path: 4 args, first 2 required
# 1st: route = contains a URL pattern (localhost:8000/'route')
# 2nd: view = calls the matched specified function
# 3rd: kwargs = ?
# 4th: name = naming your urls lets you refer to it unambigiously from elsewehere in django (templates)
urlpatterns = [
    path('webapp/', include('webapp.urls', namespace='webapp')),
    # First I had the webapp and accounts seperate, now both in webapp because to much dependency on each other
    # path('accounts/', include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
]

# To see files when debugging
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/appPackage/webapp/urls.py
from django.urls import path
from . import views

# used for namespacing applications
app_name = 'webapp'

# path: 4 args, first 2 required
# 1st: route = contains a URL pattern (localhost:8000/'route')
# 2nd: view = calls the matched specified function
# 3rd: kwargs = ?
# 4th: name = naming your urls lets you refer to it unambigiously from elsewehere in django (templates)
urlpatterns = [
    # /webapp
    path('', views.IndexView.as_view(), name='index'),
    # /webapp/*detail*
    path('model/<str:pk>/', views.DetailView.as_view(), name='detail'),
    # /webapp/upload
    path('upload/', views.UploadView.as_view(), name='upload'),
    path('files/', views.FileListView.as_view(), name='file_list'),
    path('files/<int:pk>/', views.delete_file, name='delete_file'),
    path('model/deleteanno/<int:pk>/', views.delete_anno, name='delete_anno'),
    path('model/<int:pk>/updatedesc/', views.UpdateDescView.as_view(), name='updatedesc'),
    path('model/<int:pk>/updateanno/', views.UpdateAnnoView.as_view(), name='updateanno'),
    path('model/<int:pk>/createanno/', views.CreateAnnoView.as_view(), name='createanno'),
    # For accounts 
    path("register", views.register, name='register'),
    path("login", views.login, name="login"),
    path("logout", views.logout, name="logout"),
]

app/appPackage/webapp/models.py
from os import name
from django.db import models
from django.db.models.deletion import CASCADE
import xml.etree.ElementTree as ET
from lxml import etree

from django.utils import tree

# Before saving objects to the database, we put them in an array
# Because of the structure of the XML files we cant directly add
#   To the database, because of foreign key constraint failure on
#   certain relations/components. 
modelrepresentations = []
components = []
attributes = []
operations = []
parameters = []
relations = []

# Namespaces used in XML files
namespaces = {
    'uml': 'http://schema.omg.org/spec/UML/2.0',
    'UML': 'href://org.omg/UML/1.3',
    'xmi': 'http://schema.omg.org/spec/XMI/2.1',
    }


# Create your models here.
class modelfile(models.Model):
    name = models.CharField(max_length = 100)
    file = models.FileField(upload_to='')
    # description = models.TextField(null=True, blank=True)
    
    def delete(self, *args, **kwargs):
        self.file.delete()
        super().delete(*args, **kwargs)

class modelrepresentation(models.Model):
    # Used as PK in database
    # id = models.AutoField(primary_key=True)
    # Used to find associated components
    modelid = models.CharField(max_length = 45)
    name = models.CharField(max_length = 100)
    file = models.OneToOneField(modelfile, on_delete=models.CASCADE)
    description = models.TextField(null=True, blank=True)

class component(models.Model):
    componentid = models.CharField(max_length=20)
    # id = models.CharField(max_length = 45)
    name = models.CharField(max_length = 100)
    type = models.CharField(max_length = 100)
    modelid = models.ForeignKey(modelrepresentation, on_delete=models.CASCADE)

class annotation(models.Model):
    # xposition = models.IntegerField()
    # yposition = models.IntegerField()
    content = models.TextField()
    ownerid = models.OneToOneField(component, on_delete=models.CASCADE)

class attribute(models.Model):
    attributeid = models.CharField(max_length=20)
    # id = models.CharField(max_length = 45)
    name = models.CharField(max_length = 100)
    type = models.CharField(max_length = 100)
    datatype = models.CharField(max_length = 45, null=True, blank=True)
    visibility = models.CharField(max_length = 100)
    ownerid = models.ForeignKey(component, on_delete=models.CASCADE)   

class operation(models.Model):
    operationid = models.CharField(max_length=20)
    # id = models.CharField(max_length = 45)
    name = models.CharField(max_length = 100)
    type = models.CharField(max_length = 100)
    visibility = models.CharField(max_length = 45)
    ownerid = models.ForeignKey(component, on_delete=models.CASCADE)

class parameter(models.Model):
    parameterid = models.CharField(max_length=20)
    # id = models.CharField(max_length = 45)
    name = models.CharField(max_length = 100, null = True, blank = True)
    type = models.CharField(max_length = 100)
    direction = models.CharField(max_length = 100)
    ownerid = models.ForeignKey(operation, on_delete=models.CASCADE)        

class relation(models.Model):
    relationid = models.CharField(max_length=20)
    # id = models.CharField(max_length = 45)
    name = models.CharField(max_length = 100, null = True, blank = True)
    type = models.CharField(max_length = 100)
    source = models.ForeignKey(component, on_delete=models.CASCADE, related_name='source')
    target = models.ForeignKey(component, on_delete=models.CASCADE, related_name='target')

# METHODS For saving XMLfile
####### Methods to parse and save from starUML 3 export
def findAttributesStar(root, componentId):
    for ownedAttribute in root.findall(".//*[@{http://schema.omg.org/spec/XMI/2.1}id='" + componentId + "']/ownedAttribute"):
        
        attrId = ownedAttribute.get('{http://schema.omg.org/spec/XMI/2.1}id')
        attrName = ownedAttribute.get('name')
        attrType = ownedAttribute.get('{http://schema.omg.org/spec/XMI/2.1}type')
        attrDataType = ownedAttribute.get('type')
        attrVisibility = ownedAttribute.get('visibility')

        # 
        if (attrDataType != None):
            item = root.find(".//*[@{http://schema.omg.org/spec/XMI/2.1}id='" + attrDataType + "']")
            attrDataType = item.get('name') 


        # Some attribuets are defined with a custom DataType, and stored elsewhere in the XML file with id = type
        a = attribute(attrId, attrName, attrType, attrDataType, attrVisibility, componentId)
        # a.save()
        attributes.append(a)
      
def findParametersStar(root, operationId):
    for ownedParameter in root.findall(".//*[@{http://schema.omg.org/spec/XMI/2.1}id='" + operationId + "']/ownedParameter"):
            
        parameterId = ownedParameter.get('{http://schema.omg.org/spec/XMI/2.1}id')
        parameterName = ownedParameter.get('name')
        parameterType = ownedParameter.get('{http://schema.omg.org/spec/XMI/2.1}type')
        parameterDirection = ownedParameter.get('direction')

        # Some parameters are defined with a custom DataType, and stored elsewhere in the XML file with id = type
        if (parameterName == None):
            customType = ownedParameter.get('type')
            item = root.find(".//*[@{http://schema.omg.org/spec/XMI/2.1}id='" + customType + "']")
            parameterName = item.get('name') 

        # add to database
        p = parameter(parameterId, parameterName, parameterType, parameterDirection, operationId)
        parameters.append(p)
    
def findRelationStar(root, componentId):
    for ownedRelation in root.findall(".//*[@{http://schema.omg.org/spec/XMI/2.1}id='" + componentId + "']/generalization"):
    
        relationId = ownedRelation.get('{http://schema.omg.org/spec/XMI/2.1}id')
        relationName = ownedRelation.get('name')
        relationType = ownedRelation.get('{http://schema.omg.org/spec/XMI/2.1}type')
        relationSource = ownedRelation.get('specific')
        relationTarget = ownedRelation.get('general')

        # add to database
        r = relation(relationId, relationName, relationType, relationSource, relationTarget)
        # r.save()
        relations.append(r)
    
def findOwnedMembersStar(root, componentId):
    for ownedMember in root.findall(".//*[@{http://schema.omg.org/spec/XMI/2.1}id='" + componentId + "']/ownedMember"):
            
        relationId = ownedMember.get('{http://schema.omg.org/spec/XMI/2.1}id')
        relationName = ownedMember.get('name')

        #end 1 aggregation = none           ->source or target
        #end 2 aggregation = none           ->target or source

        #end 1 aggregation = composite      ->source
        #end 2 aggregation = none           ->target

        #end 1 aggregation = none           ->target
        #end 2 aggregation = composite      ->source
        i = 0
        for ownedEnd in root.findall(".//*[@{http://schema.omg.org/spec/XMI/2.1}id='" + relationId + "']/ownedEnd"):
            currentEndType = ownedEnd.get('aggregation')
            if (currentEndType == "none"):
                if (i == 0):
                    relationTarget = ownedEnd.get('type')
                else:
                    relationSource = ownedEnd.get('type')
                    relationType = currentEndType
                i = i + 1
            else: 
                relationSource = ownedEnd.get('type')
                relationType = ownedEnd.get('aggregation')

        # add to database
        r = relation(relationId, relationName, relationType, relationSource, relationTarget)
        # r.save()
        relations.append(r)

def findOperationsStar(root, componentId):
    for ownedOperation in root.findall(".//*[@{http://schema.omg.org/spec/XMI/2.1}id='" + componentId + "']/ownedOperation"):
        
        operationId = ownedOperation.get('{http://schema.omg.org/spec/XMI/2.1}id')
        operationName = ownedOperation.get('name')
        operationType = ownedOperation.get('{http://schema.omg.org/spec/XMI/2.1}type')
        operationVisibility = ownedOperation.get('visibility')
        # print(operationVisibility)

        # TODO: add to database
        # self.operations.append({operationId, operationName, operationType, operationVisibility})
        # print("Operation: [id: %s] [name: %s] [type: %s] [visibility: %s]" % 
        #     (operationId, operationName, operationType, operationVisibility))

        # add to database
        o = operation(operationId, operationName, operationType, operationVisibility, componentId)
        # o.save()
        operations.append(o)

        findParametersStar(root, operationId)

def findComponentsStar(root, modelId):
    for ownedComponent in root.findall(".//*[@{http://schema.omg.org/spec/XMI/2.1}type='uml:Class']"):
        
        componentId = ownedComponent.get('{http://schema.omg.org/spec/XMI/2.1}id')    
        componentName = ownedComponent.get('name')
        componentType = ownedComponent.get('{http://schema.omg.org/spec/XMI/2.1}type')
        
        # add to database
        c = component(componentId, componentName, componentType, modelId)
        # c.save()
        components.append(c)

        # find associated attributes/operations/relations
        findAttributesStar(root, componentId)
        findOperationsStar(root, componentId)
        findRelationStar(root, componentId)
        findOwnedMembersStar(root, componentId)

def findModelStar(root):
    for model in root.findall(".//ownedComponent/[@{http://schema.omg.org/spec/XMI/2.1}type='uml:Model']"):
    # for model in root.findall('UML:Model')
        modelId = model.get('{http://schema.omg.org/spec/XMI/2.1}id')
        modelName = model.get('name')

        # add to database
        m = modelrepresentation(modelId, modelName)
        # m.save()
        modelrepresentations.append(m)

        # find associated components
        findComponentsStar(root, modelId)

# function to find foreign key based on found id in model
def findRelated(list, filter):
    for x in list:
        if filter(x):

app/appPackage/webapp/forms.py
from django import forms
from .models import modelfile, modelrepresentation, annotation

class FileForm(forms.ModelForm):
    class Meta:
        model = modelfile
        fields = ('name', 'file')

class ModelRepresentationForm(forms.ModelForm):
    class Meta:
        model = modelrepresentation
        fields = ('description',)

class AnnotationForm(forms.ModelForm):
    class Meta:
        model = annotation
        fields = ('content',)

app/appPackage/webapp/templates/webapp/base.html
{% load static %}

<!-- MIT Licenced template: https://startbootstrap.com/template/bare -->

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block title %}{% endblock %}</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'webapp/assets/favicon.ico' %}" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'webapp/css/styles.css' %}" rel="stylesheet" />
    <body>
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="{% url 'webapp:index' %}">Bachelor Project</a>
                <!-- {% if user.is_authenticated %}
                    <li class="navbar-text">User: {{ user.first_name }} {{ user.last_name }}</li>
                {% endif %} -->
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        {% if user.is_authenticated %}
                            <li class="navbar-text">Hello, {{ user.first_name }}&nbsp;&nbsp;&nbsp;</li>
                            <!-- <li class="nav-item"><a class="nav-link" href="#">Link</a></li> -->
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Menu</a>
                                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                    <li><a class="dropdown-item" href="{% url 'webapp:upload' %}">Upload File</a></li>
                                    <!-- <li><a class="dropdown-item" href="#">Remove File</a></li> -->
                                    <li><a class="dropdown-item" href="{% url 'webapp:file_list' %}">All Files</a></li>
                                    <li><hr class="dropdown-divider" /></li>
                                    <li><a class="dropdown-item" href="{% url 'webapp:logout' %}">Log out</a></li>
                                </ul>
                            </li>
                        {% else %}
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'webapp:login' %}">Login</a></li>
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'webapp:register' %}">Register</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page content-->
        <div class="container">
            <div id="content" class="text-center-start mt-5">
                {% block content %}
                {% endblock %}
            </div>
        </div>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'webapp/js/scripts.js' %}"></script>
    </body>
</html>

app/appPackage/webapp/templates/webapp/createanno.html
{% extends "base.html" %}

{% load static %}

{% load crispy_forms_tags %}

{% block title %} Update Page {% endblock %}

{% block content %}

<h1>Create an Annotation for {{ owner.name }}</h1>
<p>ID: {{ owner.id }}</p>
<img src="{% static 'webapp/images/graph.svg' %}" class="img-fluid mt-5" alt="Responsive image">

<br>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <br>
    <button type="submit" class="btn btn-secondary btn-sm" autofocus="True">Create</button>
</form>
<br>
<br>

{% endblock %} 

app/appPackage/webapp/templates/webapp/detail.html
{% extends "base.html" %}

{% load static %}

{% load crispy_forms_tags %}

{% block title %} Detail Page {% endblock %}

{% block content %}

<h1>{{ modelrepresentation.name}}</h1>
<p>ID: {{ modelrepresentation.id }}</p>

<img src="{% static 'webapp/images/graph.svg' %}" class="img-fluid mt-5" alt="Responsive image">
<br>
<br>


<h4>Description:</h4>
<p>{{modelrepresentation.description}}</p>

<a href="{% url 'webapp:updatedesc' modelrepresentation.id %}" class="btn btn-secondary btn-sm"> Edit description </a>
<br>
<br>
<br>


<table class="table">
    <thead>
        <tr>
            <th>Components</th>
            <th>Attributes</th>
            <th>Operations</th>
            <th>Parameters</th>
            <th>Relations</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                <ul>
                    {% for c in component_list.all %}
                        <li>{{ c.name }}<br> 
                            {% if c.id in annotated_components %}
                                {% for a in annotation_list %}
                                    {% if a.ownerid == c %}
                                        <a href="{% url 'webapp:updateanno' a.id %}" class="btn btn-success btn-sm"> Edit Annotation </a>
                                        <br>
                                        <form method="post" action="{% url 'webapp:delete_anno' a.pk %}">
                                            {% csrf_token %}
                                            <button type="submit" class="btn btn-danger btn-sm">Delete Annotation</button>
                                        </form>
                                    {% endif %}
                                {% endfor %}
                            {% else %}
                                <a href="{% url 'webapp:createanno' c.id %}" class="btn btn-secondary btn-sm"> Add Annotation </a>
                            {% endif %}
                        </li>
                    {% endfor %}
                </ul>
            </td>
            <td>
                <ul>
                    {% for a in attribute_list.all %}
                        <li>Name: {{ a.name }} </li> 
                            <!-- ID: {{ a.id }} <br> -->
                            Type: {{ a.type }} <br> 
                            <!-- DataType: {{ a.datatype }} <br>  -->
                            Owner: {{ a.ownerid.name }} <br>
                        </li>
                    {% endfor %}
                </ul>
            </td>
            <td>
                <ul>
                    {% for o in operation_list.all %}
                        <li>Name: {{ o.name }} <br>
                            <!-- ID: {{ o.id }} <br> -->
                            <!-- Type: {{ o.type }} <br>  -->
                            <!-- Visibility: {{ o.visibility}} <br>  -->
                            Owner: {{ o.ownerid.name }}
                        </li>
                    {% endfor %}
                </ul>
            </td>
            <td>
                <ul>
                    {% for p in parameter_list.all %}
                        <li>Name: {{ p.name }} <br>
                            <!-- ID: {{ p.id }} <br> -->
                            <!-- Direction: {{ p.direction }} <br>  -->
                            <!-- Type: {{ p.type }} <br> -->
                            <!-- Owner ID: {{ p.ownerid }} -->
                        </li>
                    {% endfor %}
                </ul>
            </td>
            <td>
                <ul>
                    {% for r in relation_list.all %}
                        <li>Name: {{ r.name }} <br>
                            <!-- ID: {{ r.id }} <br> -->
                            Type: {{ r.type }} <br> 
                            Source: {{ r.source.name }} <br> 
                            Target: {{ r.target.name }}
                        </li>
                    {% endfor %}
                </ul>
            </td>
        </tr>

    </tbody>
</table>

{% endblock %} 

app/appPackage/webapp/templates/webapp/file_list.html
{% extends "base.html" %}

{% load static %}

{% block title %} Files Page {% endblock %}

{% block content %}

<h1>All Files:</h1>
<table class="table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Download</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for file in file_list %}
        <tr>
            <td>{{ file.name }}</td>
            <td>
                <a href="{{ file.file.url }}"> {{file.file}} </a>
            </td>
            <td>
                <form method="post" action="{% url 'webapp:delete_file' file.pk %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger btn-sm">Delete File</button>
                </form>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %} 

app/appPackage/webapp/templates/webapp/index.html
{% extends "base.html" %}

{% load static %}

{% block title %} Index Page {% endblock %}

{% block content %}

<!-- <h1>All Models:</h1>
{% if model_list %}
    {% for modelrepresentation in model_list %}
        <h4><a href="{% url 'webapp:detail' modelrepresentation.id %}"> {{modelrepresentation.name}}</a></h4>
        <p>ID: {{ modelrepresentation.id }} - File: {{ modelrepresentation.file.name}}</p>
    {% endfor %}
{% else %}
    <p>No models are available.</p>
{% endif %} -->


<h1>Index Page:</h1>
{% if user.is_authenticated %}
    <table allign="right" class="table">
        <caption>All the models currently in the database.</caption>
        <thead>
            <tr>
                <th>Model</th>
                <th style="text-align:left">File</th>
            </tr>
        </thead>
        <tbody>
            {% if model_list %}
                {% for modelrepresentation in model_list %}
                <tr>
                    <td>
                        <a href="{% url 'webapp:detail' modelrepresentation.id %}"> {{modelrepresentation.name}} </a>
                    </td>
                    <td style="text-align:left">
                        {{ modelrepresentation.file.name}}
                    </td>
                </tr>
                {% endfor %}
            {% else %}
                <p>No models are available.</p>
            {% endif %} 
        </tbody>
    </table>
{% else %}
    <hr>
    <h5 style="color:grey; font-weight: normal;">Log in to see available models.</h5>
{% endif %}


{% endblock %} 

app/appPackage/webapp/templates/webapp/login.html
{% extends "base.html" %}

{% load static %}

{% load crispy_forms_tags %}

{% block title %} Login Page {% endblock %}

{% block content %}

<h1>Login</h1>

<br>
<div class="container">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row">
            <div class="col-25">
                <label>Username</label>
            </div>
            <div class="col-75">
                <input type="text" name="username" placeholder="Your username">
            </div>
        </div>
        <div class="row">
            <div class="col-25">
                <label>Password</label>
            </div>
            <div class="col-75">
                <input type="password" name="password" placeholder="Your password">
            </div>
        </div>
        <div>
            <br>
            <button type="submit" class="btn btn-secondary btn-sm" autofocus="True">Log in</button>
        </div>
    </form>
</div>

<br>
<div>
    {% for message in messages %}
        <p style="color:white; background-color: tomato; border-radius: 5px;">&nbsp;Error: {{ message }} </p>
    {% endfor %}
</div>

{% endblock %} 

app/appPackage/webapp/templates/webapp/register.html
{% extends "base.html" %}

{% load static %}

{% load crispy_forms_tags %}

{% block title %} Register Page {% endblock %}

{% block content %}

<h1>Register an Account</h1>

<br>
<!-- <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <p>First Name: <input type="text" name="first_name" placeholder="First Name"></p>
    <p>Last Name: <input type="text" name="last_name" placeholder="Last Name"></p>
    <p>Username: <input type="text" name="username" placeholder="Username"></p>
    <p>Email: <input type="email" name="email" placeholder="email"></p>
    <p>Password: <input type="password" name="password1" placeholder="Password"></p>
    <p>Confirm Password: <input type="password" name="password2" placeholder="Confirm Password"></p>

    <br>
    <button type="submit" class="btn btn-secondary btn-sm" autofocus="True">Register</button>
</form> -->

<div class="container">
    <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
        <div class="row">
            <div class="col-25">
                <label>First Name</label>
            </div>
            <div class="col-75">
                <input type="text" name="first_name" placeholder="Your name">
            </div>
        </div>
        <div class="row">
            <div class="col-25">
                <label>Last Name</label>
            </div>
            <div class="col-75">
                <input type="text" name="last_name" placeholder="Your last name">
            </div>
        </div>
        <div class="row">
            <div class="col-25">
                <label>Username</label>
            </div>
            <div class="col-75">
                <input type="text" name="username" placeholder="Your username">
            </div>
        </div>
        <div class="row">
            <div class="col-25">
                <label>Email</label>
            </div>
            <div class="col-75">
                <input type="email" name="email" placeholder="Your email">
            </div>
        </div>
        <div class="row">
            <div class="col-25">
                <label>Password</label>
            </div>
            <div class="col-75">
                <input type="password" name="password1" placeholder="">
            </div>
        </div>
        <div class="row">
            <div class="col-25">
                <label>Confirm password</label>
            </div>
            <div class="col-75">
                <input type="password" name="password2" placeholder="">
            </div>
        </div>
        <div>
            <br>
            <button type="submit" class="btn btn-secondary btn-sm" autofocus="True">Register</button>
        </div>
    </form>
</div>

<br>
<div>
    {% for message in messages %}
        <p style="color:white; background-color: tomato; border-radius: 5px;">&nbsp;Error: {{ message }} </p>
    {% endfor %}
</div>

<br>
<br>

{% endblock %} 

app/appPackage/webapp/templates/webapp/updateanno.html
{% extends "base.html" %}

{% load static %}

{% load crispy_forms_tags %}

{% block title %} Update Page {% endblock %}

{% block content %}

<h1>Edit the Annotation for {{ annotation.ownerid.name }} </h1> 
<p>ID: {{ annotation.ownerid.id }}</p>
<img src="{% static 'webapp/images/graph.svg' %}" class="img-fluid mt-5" alt="Responsive image">

<br>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <br>
    <button type="submit" class="btn btn-secondary btn-sm" autofocus="True">Update</button>
</form>
<br>
<br>

{% endblock %} 

app/appPackage/webapp/templates/webapp/updatedesc.html
{% extends "base.html" %}

{% load static %}

{% load crispy_forms_tags %}

{% block title %} Update Page {% endblock %}

{% block content %}

<h1>Update the Description for {{modelrepresentation.name}}</h1>
<p>ID: {{ modelrepresentation.id }}</p>
<img src="{% static 'webapp/images/graph.svg' %}" class="img-fluid mt-5" alt="Responsive image">

<br>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <br>
    <button type="submit" class="btn btn-secondary btn-sm" autofocus="True">Update</button>
</form>
<br>
<br>

{% endblock %} 

app/appPackage/webapp/templates/webapp/upload.html
{% extends "base.html" %}

{% load static %}

{% load crispy_forms_tags %}

{% block title %} Upload Page {% endblock %}

{% block content %}

<h1>Upload a File:</h1>
<br>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <br>
    <button class="btn btn-secondary btn-sm" type="submit">Upload</button>
</form>

{% endblock %} 